apiVersion: v1
kind: Service
metadata:
  name: react-portfolio
  namespace: react-portfolio
  labels:
    app: react-portfolio
spec:
  type: ClusterIP
  selector:
    app: react-portfolio
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
